const frases = [
  { id: 1, desc: "A jornada à frente revela promessas de novas conexões." },
  { id: 2, desc: "Enfrente seus medos e você descobrirá o seu verdadeiro poder." },
  { id: 3, desc: "As melhores coisas da vida surgem das mudanças mais inesperadas." },
  { id: 4, desc: "Cultive a paciência e você colherá frutos adocicados." },
  { id: 5, desc: "Um momento de gratidão faz a diferença em qualquer dia." },
  { id: 6, desc: "Sua maior aventura está apenas a um passo de distância." },
  { id: 7, desc: "Confie na sua intuição; ela é sua guia mais confiável." },
  { id: 8, desc: "A verdadeira coragem é perseverar mesmo quando o caminho é incerto." },
  { id: 9, desc: "O riso é um bálsamo para o espírito; compartilhe-o generosamente." },
  { id: 10, desc: "Abra seu coração para novas pessoas e novas experiências." },
  { id: 11, desc: "Cada dia é uma tela em branco; pinte sua obra-prima." },
  { id: 12, desc: "As palavras gentis podem ser curtas, mas seus ecos são eternos." },
  { id: 13, desc: "Lembre-se, os obstáculos no caminho são apenas desvios no topo." },
  { id: 14, desc: "Permita-se sonhar grande e esforce-se para tornar isso realidade." },
  { id: 15, desc: "A sabedoria vem com a experiência; valorize cada lição." },
  { id: 16, desc: "A felicidade muitas vezes se esgueira através de uma porta que você não sabia que havia deixado aberta."},
  { id: 17, desc: "Encare cada desafio como uma oportunidade para crescer." },
  { id: 18, desc: "A solidariedade pode transformar o mundo, comece com um pequeno gesto." },
  { id: 19, desc: "Seja um farol de esperança e positividade em um mundo de incertezas." },
  { id: 20, desc: "Nunca subestime o poder de um momento de silêncio." },
]
